# Generated by Django 4.0 on 2023-03-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_data_cadastro_user_userdata_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserData_cadastro',
            new_name='Data_cadastro',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserData_nascimento',
            new_name='Data_nascimento',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserNome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserSobrenome',
            new_name='Sobrenome',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='User',
        ),
    ]
